## Append samples of your project ##
resources:
- core_sample_namespace.yaml
- core_v1alpha1_staging.yaml
# Resources below disabled until implementation is in place
# - core_v1alpha1_staging_trigger.yaml
# - core_v1alpha1_trigger.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
